[package]
name = "drawing"
version = "0.1.0"
authors = ["Marek G <no@mail.com>"]
description = "Drawing library"
edition = "2018"

[dependencies]
bitflags = "1.2.1"
failure = "0.1"
euclid = "0.20"
freetype-rs = "0.23"
rawpointer = "0.2.1"
clamped = "1.0.0"
