[package]
name = "drawing"
version = "0.1.0"
authors = ["Marek G <no@mail.com>"]
description = "Drawing library"
edition = "2018"

[dependencies]
failure = "0.1"
winit = "0.20.0-alpha4"
euclid = "0.20"
freetype-rs = "0.23"
