[package]
name = "drawing"
version = "0.1.0"
authors = ["Marek G <no@mail.com>"]
description = "Drawing library"
edition = "2018"

[dependencies]
failure = "*"
winit = "*"
#winit = { git = "https://github.com/marek-g/winit" }
euclid = "*"
image = "*"
freetype-rs = "*"
